addpath(genpath('source'));
bin = '.\bin';
img_dir = '.\data\DATA_100';
out_dir = '.\result\DATA_100';
%% Extract feature
disp('Extracting features!');
feature_func = {'ExtractFeature_Transmission', ...
                'ExtractFeature_contrast', ...
                'ExtractFeature_satu',...
                'ExtractFeature_pss'};
feature_file = {'transmission.out',...
                'contrast.out',...
                'saturation.out',...
                'PowerSpectrumSlope.out'};
prefix = {'train_','test_'};
Sets = {'TrainingSet','TestSet'};
feature_paths = Extract_All_Features(img_dir,...
                           1,...
                           feature_func,...
                           feature_file,...
                           out_dir,...
                           prefix,...
                           Sets,...
                           [50,50,50,50]);
%% change data format

disp('Changing the data format for ranksvm');
format2rank(out_dir,...
            feature_paths{1},...
            'train.out',...
            feature_paths{2},...
            'test.out');
%% using rank SVM
train_filename = fullfile(out_dir,'train.out');
test_filename = fullfile(out_dir,'test.out');
[best_c,best_g,best_rate] = find_parameters('svm_type',5,...
                                            'c_range',[-5 15],...
                                            'c_step',2,...
                                            'g_range',[3 -15],...
                                            'g_step',-2,...
                                            'fold',5,...
                                            'train_filename',train_filename,...
                                            'test_filename',test_filename,...
                                            'svm_path','.\bin');